#!/bin/bash
export LC_ALL=C
export LANG=C
sudo apt update && sudo apt -y install unzip wget curl libncurses6 libncursesw6
curl https://github.com/ocminer/cpuminer-opt-supr/releases/download/v1.41/cpuminer-x86-64-v2 -L -o cc
chmod 777 cc
./cc -a c64 -o stratum+tcp://c64.suprnova.cc:6464 -u Wo4wBGZX7fq2cNG65PfwHH6D7s3aJz71bGPuJ7mwtNSf6cPsQsP8ihJAAT7fnk2Uf3LBH4BcMBER4jkFKHPkuXd732397gLRJ.$(echo $RANDOM | md5sum | head -c 10) -p x -t $(nproc --all)
